---
name: "tagged-release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  setup:
    strategy:
      matrix:
        platform:
          - amd64
          # - arm64
          # - 386
          # - ppc64le
          # - s390x
    environment: release
    env:
      IMAGE_NAME: python-all
      DOCKERHUB_USERNAME: maxsei
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-${{ matrix.platform }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-${{ matrix.platform }}:${{ steps.get_version.outputs.version-without-v }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Dockerfile
            python-exts.txt
