---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"
jobs:
  docker:
    env:
      IMAGE_NAME: "python-all"
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ steps.get_version.outputs.version-without-v }}
            ghcr/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
            ghcr/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ steps.get_version.outputs.version-without-v }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Dockerfile
            python-exts.txt
